### ISSUE TITLE
Support 32-bit floats.

### ISSUE THREAD

**Issue by tgregg** [amzn/ion-c#139]
Currently, the binary reader [raises IERR_INVALID_BINARY](https://github.com/amzn/ion-c/blob/master/ionc/ion_binary.c#L389) for all float values that don't declare length 8. However, 32-bit floats (length 4) are also allowed.

Read support should be prioritized. Write support can also be added.

**Comment by tgregg** [comment]
Read support has been added via `ion_reader_read_double` in #155 

Leaving this issue open for the remaining task: adding a writer API to write 32-bit floats.

**Comment by abhinuvpitale** [comment]
Can I try the writing the writer API?

**Comment by tgregg** [comment]
@abhinuvpitale Of course!

**Comment by nikhilsr** [comment]
Is there a timeline for support of writing float values yet?

**Comment by jobarr-amzn** [comment]
@nikhilsr For clarification, `ion-c` presently supports writing C float types as [Ion floats](https://amzn.github.io/ion-docs/docs/float.html), but they are written using the IEEE-754 `binary64` encoding. 

This issue is about adding a writer API to support writing floating point types using the fewer bits of the IEEE-754 `binary32` encoding.

We presently have no timeline for the latter, but I'll take a look.

**Comment by jobarr-amzn** [comment]
This should be resolved by PR #232 . A future change will add an option to enable writing `double` values as 32-bit floats when it's losslessly possible.
