### ISSUE TITLE
Redefinition of windows types

### ISSUE THREAD

**Issue by derivativerobmc** [amzn/ion-c#172]
I'm trying to include ionc into an existing project that includes some standard windows headers. However, I'm getting naming conflicts with a couple of the types: SID, already defined in winnt.h, and SIZE, already defined in windef.h.

Is there a workaround for this, or thoughts about using more unique type names?

**Comment by therapon** [comment]
Long term solution should be a naming convention to minimize conflicts, e.g., prefixing names with Ion. 

In the mean time,

1.  if you are using a C++ compiler for your project you could use `namespaces` see this [SO question](https://stackoverflow.com/questions/32582933/how-to-avoid-variable-function-conflicts-from-two-libraries-in-c)
1. if you are using a C compiler then you can use the C preprocessor to wrap and provide different names, see this [SO question](https://stackoverflow.com/questions/53855784/what-is-the-standard-way-to-fix-conflicting-types-from-different-libraries-in-c)
1. If possible, you could separate the code that uses the 2 conflicting names into separate files so that you include 1 but not both in each file. 

HTH

**Comment by derivativerobmc** [comment]
Thank you very much for the suggestions. I did look at a couple of those methods a little last week, but for the moment just settled on adding ION_ to the types in my includes to get things going quickly.

**Comment by therapon** [comment]
Created an issue about naming convention especially for exported names and we can track there. Feel free to re-open this issue if there are still questions.
